export const supportedCountries = [
	{ name: 'Argentina', code: 'ar' },
	{ name: 'Australia', code: 'au' },
	{ name: 'Austria', code: 'at' },
	{ name: 'Belgium', code: 'be' },
	{ name: 'Brazil', code: 'br' },
	{ name: 'Canada', code: 'ca' },
	{ name: 'China', code: 'cn' },
	{ name: 'France', code: 'fr' },
	{ name: 'Germany', code: 'de' },
	{ name: 'India', code: 'in' },
	{ name: 'Italy', code: 'it' },
	{ name: 'Japan', code: 'jp' },
	{ name: 'Mexico', code: 'mx' },
	{ name: 'Netherlands', code: 'nl' },
	{ name: 'Nigeria', code: 'ng' },
	{ name: 'Russia', code: 'ru' },
	{ name: 'Saudi Arabia', code: 'sa' },
	{ name: 'South Korea', code: 'kr' },
	{ name: 'United Kingdom', code: 'gb' },
	{ name: 'United States', code: 'us' },
];
